/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Jul 02 00:28:59 CDT 2015
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist CallType
 */
public enum CallTypeEnum {

    // Internal
    INTERNAL("Internal"),
    // Inbound
    INBOUND("Inbound"),
    // Outbound
    OUTBOUND("Outbound");

    final String value;

    private CallTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static CallTypeEnum fromValue(String value) {
        for (CallTypeEnum e : CallTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}