/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Jul 02 00:28:59 CDT 2015
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist CampaignAccessLevel
 */
public enum CampaignAccessLevelEnum {

    // Read
    READ("Read"),
    // Edit
    EDIT("Edit"),
    // All
    ALL("All");

    final String value;

    private CampaignAccessLevelEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static CampaignAccessLevelEnum fromValue(String value) {
        for (CampaignAccessLevelEnum e : CampaignAccessLevelEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}