/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Jul 02 00:28:59 CDT 2015
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist CleanStatus
 */
public enum CleanStatusEnum {

    // Matched
    MATCHED("Matched"),
    // Different
    DIFFERENT("Different"),
    // Acknowledged
    ACKNOWLEDGED("Acknowledged"),
    // NotFound
    NOTFOUND("NotFound"),
    // Inactive
    INACTIVE("Inactive"),
    // Pending
    PENDING("Pending"),
    // SelectMatch
    SELECTMATCH("SelectMatch"),
    // Skipped
    SKIPPED("Skipped");

    final String value;

    private CleanStatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static CleanStatusEnum fromValue(String value) {
        for (CleanStatusEnum e : CleanStatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}