/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Jul 02 00:28:59 CDT 2015
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist DefaultCalendarAccess
 */
public enum DefaultCalendarAccessEnum {

    // HideDetails
    HIDEDETAILS("HideDetails"),
    // HideDetailsInsert
    HIDEDETAILSINSERT("HideDetailsInsert"),
    // ShowDetails
    SHOWDETAILS("ShowDetails"),
    // ShowDetailsInsert
    SHOWDETAILSINSERT("ShowDetailsInsert"),
    // AllowEdits
    ALLOWEDITS("AllowEdits");

    final String value;

    private DefaultCalendarAccessEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static DefaultCalendarAccessEnum fromValue(String value) {
        for (DefaultCalendarAccessEnum e : DefaultCalendarAccessEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}