/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Jul 02 00:28:59 CDT 2015
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist DeliveryInstallationStatus__c
 */
public enum DeliveryInstallationStatusEnum {

    // In progress
    IN_PROGRESS("In progress"),
    // Yet to begin
    YET_TO_BEGIN("Yet to begin"),
    // Completed
    COMPLETED("Completed");

    final String value;

    private DeliveryInstallationStatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static DeliveryInstallationStatusEnum fromValue(String value) {
        for (DeliveryInstallationStatusEnum e : DeliveryInstallationStatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}