/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Jul 02 00:28:59 CDT 2015
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Field
 */
public enum FieldEnum {

    // created
    CREATED("created"),
    // Description
    DESCRIPTION("Description"),
    // feedEvent
    FEEDEVENT("feedEvent"),
    // IsActive
    ISACTIVE("IsActive"),
    // IsArchived
    ISARCHIVED("IsArchived"),
    // IsStandard
    ISSTANDARD("IsStandard"),
    // Name
    NAME("Name"),
    // ownerAccepted
    OWNERACCEPTED("ownerAccepted"),
    // ownerAssignment
    OWNERASSIGNMENT("ownerAssignment"),
    // locked
    LOCKED("locked"),
    // unlocked
    UNLOCKED("unlocked");

    final String value;

    private FieldEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static FieldEnum fromValue(String value) {
        for (FieldEnum e : FieldEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}