/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Jul 02 00:28:59 CDT 2015
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist PrincipalType
 */
public enum PrincipalTypeEnum {

    // Anonymous
    ANONYMOUS("Anonymous"),
    // PerUser
    PERUSER("PerUser"),
    // NamedUser
    NAMEDUSER("NamedUser");

    final String value;

    private PrincipalTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static PrincipalTypeEnum fromValue(String value) {
        for (PrincipalTypeEnum e : PrincipalTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}