/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Jul 02 00:28:59 CDT 2015
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Role
 */
public enum RoleEnum {

    // Business User
    BUSINESS_USER("Business User"),
    // Decision Maker
    DECISION_MAKER("Decision Maker"),
    // Economic Buyer
    ECONOMIC_BUYER("Economic Buyer"),
    // Economic Decision Maker
    ECONOMIC_DECISION_MAKER("Economic Decision Maker"),
    // Evaluator
    EVALUATOR("Evaluator"),
    // Executive Sponsor
    EXECUTIVE_SPONSOR("Executive Sponsor"),
    // Influencer
    INFLUENCER("Influencer"),
    // Technical Buyer
    TECHNICAL_BUYER("Technical Buyer"),
    // Other
    OTHER("Other");

    final String value;

    private RoleEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static RoleEnum fromValue(String value) {
        for (RoleEnum e : RoleEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}