/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Jul 02 00:28:59 CDT 2015
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Subject
 */
public enum SubjectEnum {

    // Call
    CALL("Call"),
    // Email
    EMAIL("Email"),
    // Meeting
    MEETING("Meeting"),
    // Send Letter/Quote
    SEND_LETTER_QUOTE("Send Letter/Quote"),
    // Other
    OTHER("Other");

    final String value;

    private SubjectEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static SubjectEnum fromValue(String value) {
        for (SubjectEnum e : SubjectEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}